"""Typed contracts for tool I/O, citations, and coverage (T002).

These pydantic models are the source of truth for every tool boundary:
frozen, strictly validated, and JSON round-trippable.
"""

from copilot.contracts.base import ContractModel
from copilot.contracts.chat import ChatRequest, ChatResponse
from copilot.contracts.coverage import (
    CategoryCoverage,
    CoverageOk,
    CoverageUnavailable,
    CoverageVerifiedEmpty,
)
from copilot.contracts.reconciliation import (
    InteractionCheck,
    MedicationConflict,
    MedicationReconciliation,
    ReconciledMedication,
    SourceStatus,
)
from copilot.contracts.refs import FhirResourceType, ResourceRef
from copilot.contracts.tools import (
    AllergyRecord,
    ConditionRecord,
    DateRangeMixin,
    DocumentRecord,
    EncounterRecord,
    GetEncountersSinceInput,
    GetEncountersSinceOutput,
    GetImmunizationsInput,
    GetImmunizationsOutput,
    GetMedicationHistoryInput,
    GetMedicationHistoryOutput,
    GetPatientSnapshotInput,
    ImmunizationRecord,
    MedicationRecord,
    ObservationRecord,
    OutputRecord,
    PatientRecord,
    PatientSnapshotOutput,
    QueryReceipt,
    SearchDocumentsInput,
    SearchDocumentsOutput,
    SNAPSHOT_CATEGORIES,
    SearchObservationsInput,
    SearchObservationsOutput,
    ToolInput,
)
from copilot.contracts.verification import (
    ClaimStatus,
    ClaimVerdict,
    NumericCheck,
    NumericFinding,
    ResourceFacts,
    StrippedClaim,
    VerificationCounts,
    VerificationVerdict,
)

__all__ = [
    "ClaimStatus",
    "ClaimVerdict",
    "NumericCheck",
    "NumericFinding",
    "ResourceFacts",
    "StrippedClaim",
    "VerificationCounts",
    "VerificationVerdict",
    "AllergyRecord",
    "CategoryCoverage",
    "ChatRequest",
    "ChatResponse",
    "ConditionRecord",
    "ContractModel",
    "CoverageOk",
    "CoverageUnavailable",
    "CoverageVerifiedEmpty",
    "DateRangeMixin",
    "DocumentRecord",
    "EncounterRecord",
    "FhirResourceType",
    "GetEncountersSinceInput",
    "GetEncountersSinceOutput",
    "GetImmunizationsInput",
    "GetImmunizationsOutput",
    "GetMedicationHistoryInput",
    "GetMedicationHistoryOutput",
    "GetPatientSnapshotInput",
    "ImmunizationRecord",
    "InteractionCheck",
    "MedicationConflict",
    "MedicationReconciliation",
    "MedicationRecord",
    "ObservationRecord",
    "ReconciledMedication",
    "SNAPSHOT_CATEGORIES",
    "SourceStatus",
    "OutputRecord",
    "PatientRecord",
    "PatientSnapshotOutput",
    "QueryReceipt",
    "ResourceRef",
    "SearchDocumentsInput",
    "SearchDocumentsOutput",
    "SearchObservationsInput",
    "SearchObservationsOutput",
    "ToolInput",
]
